const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "254769279076"
const SESSION_ID = "PRABATH-MD~yeAmnaoQ#st3MPrOSa3yzoR09Gs4Steu-rdPc6pIVOj5b4IwSRTA"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
